# Change these first
owner: papurika-eu # Your GitHub organization or username, where this repository lives
repo: uptime-papurika # The name of this repository

sites:
  - name: Homepage
    url: https://www.papurika.eu
  - name: Opus
    url: https://opus.papurika.eu
  - name: Thot
    url: https://thot.papurika.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.papurika.eu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Papurika
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
